### ISSUE TITLE
`brew doctor` complaining about file

### ISSUE THREAD

**Issue by sidferreira** [wix/homebrew-brew#10]
```
Warning: Found Ruby file outside wix/brew tap formula directory.
(/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Formula):
  /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb
```

Not sure if it is fixable, but it is the only issue my `brew doctor` reports...

**Comment by mjstelly** [comment]
Same issue.
```
Warning: Found Ruby file outside wix/brew tap formula directory.
(/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/Formula):
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb
```
No idea what this means.

**Comment by sidferreira** [comment]
I think the rb file must go inside the Formula folder

**Comment by d4vidi** [comment]
Hey @sidferreira, is this right after installing a fresh `applesimutils`, or have you been using it for a while? Does it work for you, regardless?

**Comment by sidferreira** [comment]
> Hey @sidferreira, is this right after installing a fresh `applesimutils`, or have you been using it for a while? Does it work for you, regardless?

Using for a good while, works like a charm.

I'll reinstall later just in case
