### ISSUE TITLE
No available formula or cask with the name "wix/applesimutils".

### ISSUE THREAD

**Issue by lagparty** [wix/homebrew-brew#9]
I can't install "wix/applesimutils" anymore. Is it deprecated?

**Comment by d4vidi** [comment]
You're suppose to install `applesimutils` (no prefix):
```
brew tap wix/brew
brew install applesimutils
```
https://github.com/wix/AppleSimulatorUtils#installing

**Comment by lagparty** [comment]
Thanks, that fixed it for me.
